# Generated by Django 5.2.8 on 2025-11-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=59)),
                ('city', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=5)),
            ],
        ),
    ]
